version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.13"
  jobs:
    install:
      - python -m pip install --no-cache-dir "pip >= 25.1"
      - python -m pip install --upgrade --upgrade-strategy only-if-needed --no-cache-dir --group doc .

sphinx:
  configuration: docs/conf.py
  fail_on_warning: true
